{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-ui" "talos-operator" }}
  labels:
    {{- include "talos-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http-ui
      protocol: TCP
      name: http-ui
  selector:
    {{- include "talos-operator.selectorLabels" . | nindent 4 }}
{{- end }}